services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
  app:
    build: ./app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - api
    environment:
      API_URL: http://api:3000
